name: Deploy to Amazon Lightsail

on:
  push:
    branches:
      - master

jobs:
  deploy-by-ssh:
    name: SSH Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Use pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7
        run_install: false

    - run: pnpm install --frozen-lockfile
    - run: pnpm run build

    - name: Copy file using ssh key
      uses: appleboy/scp-action@v0.1.2
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_KEY }}
        port: 22
        source: "build/*,test.Dockerfile,docker-compose.test.yml"
        target: "~/html/remix-app"

    - name: Executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_KEY }}
        port: 22
        script_stop: true
        script: |
          cd ~/html/remix-app
          sudo docker-compose -f docker-compose.test.yml up --build -d
          sudo docker system prune -f
